### PR TITLE
Switched to nginx proxy template.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by carlalexander** [comment]
I'll have to run some tests on this. I was having issues when I was testing #29.

**Comment by carlalexander** [comment]
Alright, got time to test the PR this morning. Couldn't reproduce the issue I was having in #29. I had to rebase your branch then merge it in. Not sure why GitHub didn't pick it up though. I'm glad that it's working though!

**Comment by ypid** [comment]
Nice. You can GitHub force to recognize it by using a commit message like this "Merge pull request #36 from ypid/nginx-proxy-tmpl. Merged #36." for bb7035c1223f7c8e709e36aecbc86e270846b044.

**Comment by carlalexander** [comment]
Ah I see! I figured it was smart enough to figure that out since it's the same format as fast-forward merges. Apparently not :unamused:

**Comment by ypid** [comment]
Maybe in the future. I remember that there is an issue tracker for that but I am to lazy now. BTW, a fast-forward merge would not have any merge commit :smile:

**Comment by carlalexander** [comment]
Right sorry, I meant --no-ff!

**Pull request closed without merging**
