### PR TITLE
Rework.

### PR DESCRIPTION
**Pull request by ypid**
See: https://github.com/ypid/debops-wordpress/blob/rework/roles/wordpress/CHANGES.rst

### CODE REVIEW

**Comment by ypid** [comment]
@carlalexander If you don’t want to merge everything right away ok. You can cherry-pick some commits then.

**Comment by carlalexander** [comment]
There's merge conflicts so I'll have to look at what to do.

**Comment by ypid** [comment]
Your changes on master are very small so merge conflicts should be no issue I hope.

**Comment by ypid** [comment]
Also, before merging you might want to release version 0.1.0 e.g. create a tag?

**Comment by carlalexander** [comment]
Not sure how useful tags will be. DebOps doesn't use tags so it's a bit hard to manage at the moment.

**Comment by ypid** [comment]
DebOps uses tags but it is not integrated into the tools as far as I know (I don’t really use them yet). But for breaking changes and Ansible Galaxy there are tags and releases.

**Comment by carlalexander** [comment]
Why `CHANGES.rst` vs `CHANGES.md`?

**Comment by drybjed** [comment]
Yup, current DebOps scripts pull latest changes straight from master branches, but you could set up your own `requirements` file and pick out specific tags from the roles. And if you install roles using `ansible-galaxy` command, it picks out latest tags (if a role is tagged). So I imagine you could either method for desired effect.

**Comment by carlalexander** [comment]
Do you have an example @drybjed?

**Comment by ypid** [comment]
`CHANGES.rst` is used in the DebOps documentation.

**Comment by drybjed** [comment]
@carlalexander An example of what exactly? A requirements file?

**Comment by carlalexander** [comment]
Yeah, is it for Ansible or for DebOps?

**Comment by carlalexander** [comment]
@ypid What are all the tags for? I don't think the rest of DebOps does it that way?

**Comment by drybjed** [comment]
Right now DebOps scripts use a [requirements file](https://github.com/debops/debops-playbooks/blob/master/galaxy/requirements.txt) compatible with Ansible Galaxy. I wanted to create [an alternative file](https://github.com/debops/debops-playbooks/blob/master/galaxy/requirements-testing.txt) but that didn't really pick up.

The problem for me is that I don't really care for older versions of roles, I want to use the latest ones for  my infratructure, where all the known issues are fixed. But I imagine that projects like `debops-wordpress` would prefer more stable roles, that's why I started tagging them.

Simple way to pick role versions would be something like:

```
debops.nginx,v0.1.1
debops.mariadb_server,v0.2.0
```

And so on. Just be aware that not all roles are tagged yet, I tend to tag them when documentation is written or a significant change happens.

**Comment by ypid** [comment]
> What are all the tags for? I don't think the rest of DebOps does it that way?

The project starts to use them. This is the new format from @drybjed

**Comment by carlalexander** [comment]
Ok, this is excellent @drybjed! I need to add those in for sure.

**Comment by drybjed** [comment]
@carlalexander One problem you might face is that current DebOps scripts don't really have support for different requirements files (no way to select which one to use, AFAIR). You probably can specify different `debops-playbooks` repository and include `requirements` there. I guess current DebOps scripts aren't very user friendly, I tend to focus more on Ansible and roles rather than the scripts which for me are basically "done". But a better CLI environment would probably be a welcome improvement to the project. :)

**Comment by carlalexander** [comment]
Yeah, for sure!

**Comment by carlalexander** [comment]
I'm not going to do a tag for this. There's too many changes all over the place and didn't track beforehand. This will be `v0.1.0`. 

In the future, I'd like it PRs to be standalone so it's easy to look over everything. This is messy to merge in a sane way. Maybe it's just because of all the tag and commenting changes. That said, I'm SUPER happy with those and you taking the time to do them.

I'm currently making new commits for each role you reworked and running tests. Not everything is working right now so fixing issues as I find them. For example, you changed the default from `wordpress_ssl` to `True`.

**Comment by carlalexander** [comment]
Running into issues testing Varnish. It looks like the repo isn't working. The download keeps timing out. That's even if I try to download [the file](https://repo.varnish-cache.org/ubuntu/pool/varnish-4.1/v/varnish/varnish_4.1.0-1~trusty_amd64.deb) by hand.

One thing that I didn't include is the conditional `upstream.yml`. You turned it off by default which is ok, but that means we can't consistently get Varnish 4. That's no good for most users who need to go and turn upstream on. I figure we can either revisit in a ticket or leave it for merging varnish upstream to DebOps.

**Comment by carlalexander** [comment]
The proxy template just isn't working when `ssl` is `False`. Tried a few different option combos, but nothing works. All that gets generated is an HTTPS redirect block which isn't even correct. There shouldn't even be a redirect block here.

``` nginx
# This file is managed remotely, all changes will be lost

# nginx server configuration for:
#    - http://dev.carlalexander.ca/
# generated by Ansible role: carlalexander.wordpress

server {
        listen 80 default_server ipv6only=off;

        server_name dev.carlalexander.ca;

        return 301 https://$host$request_uri;

}
```

Another thing that stood out is that you added directives to force SSL admin over HTTP. We can't do that by default. I took it out and we can review in another ticket. That said, this is something we should support.

**Comment by carlalexander** [comment]
So far, the reworks of `wpcli`, `hhvm` and `varnish` roles seem to be fine. Like I said, I made a few changes, but overall it looks great. 

I mentioned a BC break for `mariadb` in #9. The `wordpress` role doesn't work because of the `proxy` template issues. I'll need to investigate what's going on there.

**Comment by ypid** [comment]
> In the future, I'd like it PRs to be standalone so it's easy to look over everything.

That would probably have resulted in 10 PRs or so and it would probably have caused real merge conflicts … So there is a trade-off. That’s why I decided to to it in one rework branch. You can still track my work flow via the individual commits and review them individual.

> For example, you changed the default from wordpress_ssl to True.

This makes sense as discussed here: https://github.com/carlalexander/debops-wordpress/issues/1#issuecomment-147125700

> [Varnish] One thing that I didn't include is the conditional upstream.yml.

Not sure I understand you. When you look closely you will see that I only very selectively disabled upstream by default.

https://github.com/ypid/debops-wordpress/blob/23a0888d3e2bc1a86ce1cac252ee9f851d1360b5/roles/varnish/tasks/main.yml#L6-L11

PS: Nice that you like my rework anyway :smile:

**Comment by carlalexander** [comment]
Yep, I saw that in the Varnish task. I misread it though. The only thing that sticks out is we'd have to do this for every compatible release. I also don't understand why we want an option to disable it. Should we just make it `not(ansible_distribution == 'Debian'  and ansible_distribution_release in ['jessie'])`.

The comment on TLS I misunderstood. We cannot force someone to have a SSL certificate.

**Comment by carlalexander** [comment]
What I'm going to do is tag a `v0.1.0`. I'm going to work on merging all your changes without the mariadb or proxy template changes. This is going to give us a good base to work on for these two remaining issues.

**Comment by ypid** [comment]
> not(ansible_distribution == 'Debian' and ansible_distribution_release in ['jessie'])

No because when someone wants a different version then the version from jessie should not be used IMHO.

**Comment by carlalexander** [comment]
Then why not just do it for everyone?

**Comment by ypid** [comment]
Setting wordpress_ssl: False works as expected. Does not work for you?

**Comment by ypid** [comment]
> Then why not just do it for everyone?

Everyone? I tested with Jessie and it works nicely. No need to use upstream on jessie. I did not change this for other dists/releases. There upstream is still being used.

**Comment by carlalexander** [comment]
So I just pushed four commits with the changes for the `hhvm`, `varnish`, `wordpress`, `wpcli` roles. These do not include:
- Switching to the proxy template
- Switching to the `debops.mariadb` role
- Supporting SSL admin
- Plugin management

I've spent a lot of time testing with various different configurations to ensure everything was still working. I'll need to run a lot of tests for those changes as well so I'd rather handle them one at a time. You can keep working on your branch if you want. I'll merge those changes over time as well or you can create clean PRs for them.

I'll keep this PR open for now. Let me know if I missed anything.

**Comment by ypid** [comment]
@carlalexander Sorry for the hard time I gave you with this big patch. I am now going over it and submitting the remaining changes in little pieces as requested. One thing: When you commit the work of other people you can tell git to set there name as author (you will still be the commiter). So that we know in the future who to blame :smile:

**Comment by carlalexander** [comment]
Sorry, that's my bad! I didn't think of it.

**Comment by ypid** [comment]
All features are now individual PRs. Closing this one. Nice job by the way merging this rework :+1:  With the other PRs merged, this rework is fully in master.

Sorry again for the big patch.

**Comment by carlalexander** [comment]
Thank you for your work! Yeah, it was a bit unwieldy, but it's a lot better now that all the documentation/rework commits are in. :smile:

**Comment by ypid** [comment]
Thanks.

**Pull request closed without merging**
