### PR TITLE
Replaced wired character (c2) with space.

### PR DESCRIPTION
**Pull request by ypid**
Can be checked via Vim with `:set list` and `:normal g8`.

### CODE REVIEW

**Comment by carlalexander** [comment]
Thanks! I've had these weird characters appear before, but I can't see them in Sublime.

**Comment by ypid** [comment]
You are welcome. You also had Windows encoding in the changlog file.

**Comment by carlalexander** [comment]
It's weird because I only use a Mac. I'm thinking it might be a bug with the unofficial French Canadian keyboard layout I'm using.

**Comment by ypid** [comment]
Just stumbled across this byte sequence again and it is not that wired (but still uncommon in "code", in documentation I am all for using it when appropriate). I should have known. It is [U+00A0 NO-BREAK SPACE](https://en.wikipedia.org/wiki/Non-breaking_space).

**Pull request merged**
