### PR TITLE
Update to redesigned Content Security Policy support of debops.nginx

### PR DESCRIPTION
**Pull request by ypid**
@carlalexander Can you merge this on 2017-04-15 so that it works seamlessly with the redesigned interface? Your feedback is very much welcome on the matter even after the Apache changes have already been merged.

Depends on: https://github.com/debops/ansible-nginx/pull/156

### CODE REVIEW

**Comment by ypid** [comment]
@carlalexander debops.nginx v0.2.0 has been released. Can you check this PR?

**Comment by carlalexander** [comment]
I'll try to check this tomorrow. Sorry busy today 😞

**Comment by carlalexander** [comment]
My first run at testing this PR didn't work. The site was unavailable to connect. `debops.nginx` seems to be working alright, but there might be stuff missing. Do we have to configure `debops.ferm` ourselves now?

I also ran into [this issue](https://github.com/debops/ansible-postfix/issues/84) with `debops.postfix`. Might need to find a way to remove it as well.

**Comment by ypid** [comment]
> Do we have to configure debops.ferm ourselves now?

[Yes, I removed them finally](https://github.com/debops/ansible-nginx/blob/master/CHANGES.rst#debopsnginx-v020---2017-04-15) in compliance with https://github.com/debops/debops-playbooks/issues/192. I did not check the used playbooks initially. I have currently no deployment of wordress. Updated.

**Comment by carlalexander** [comment]
This seems to be working alright. I'm running into issue with `debops.php` and `debops.fail2ban`, but it's not related to these changes.

**Pull request merged**
