### PR TITLE
Switched to `debops.mariadb`. Closes #9.

### LINKED ISSUE #9: Replace mariadb role with debops.mariadb
Now that DebOps supports Mariadb, there's no need for this project to have its own role.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by carlalexander** [comment]
This was working when I was testing #29. I just need to run tests to see what happens when the old `mariadb` role was already used and you run the updated playbook.

**Comment by carlalexander** [comment]
Ran some tests on this tonight to see the behaviour before and after merging the change. Here's what I found. I want to create an upgrade document so I'm documenting all of this.

`debops.mariadb` will reset the existing `root` password from the old role. The one found under `credentials/{ansible_fqdn}/mariadb/root/password` doesn't work anymore. You have to use the one under `fqdn/mariadb/localhost/root/password`. You can just delete the old one.

`debops.mariadb` also creates a new password for the `wordpress` user under `mariadb/{{ ansible_fqdn }}/credentials/wordpress/password`. This password doesn't match the one under `credentials/{ansible_fqdn}/mariadb/wordpress/password` even though the `wordpress` role passes the existing password to `debops.mariadb`. 

I'd expect both passwords to be the same. It can't replace the old password because the site would break. Is this a bug or misconfiguration on our part? Not sure. At worst, we can change the password in the files manually so that both match.

Otherwise, the script didn't have any issues.

**Comment by ypid** [comment]
You could maybe write a play which uses a copy task delegated to localhost (or directly run it against localhost) which copies the old password files to the new location to preserve backwards compatibility …

Edit: A simple shell script might be easier for this task.

**Comment by carlalexander** [comment]
Yeah, maybe. I feel an upgrade document is enough. Just not sure if it's a bug or something. Any thoughts @drybjed?

**Comment by drybjed** [comment]
@carlalexander You can check how the new `debops.mariadb` passwords are handled in [debops.librenms](https://github.com/debops/ansible-librenms/blob/master/defaults/main.yml#L199-L202) role. I've moved them to a central location in `secret/` directory so that different remote/local hosts can access them easily using the same path.

I think copying the password manually before running the new role should be enough to handle the switch. New installations will use the new location by default.

**Comment by carlalexander** [comment]
Cool! Thanks @drybjed. I'll look into that when I make the migration document. For now, I'll merge this since it works besides these little kinks.

**Pull request merged**
