### PR TITLE
Make wpcli role ready to be switched to package based install.

### PR DESCRIPTION
**Pull request by ypid**
@carlalexander The comments don’t hurt anyone and they are actually well tested …

### CODE REVIEW

**Comment by carlalexander** [comment]
I would rather have a ready-to-commit PR. We can just keep this open until the new version of wp-cli comes out. Then we can just merge it.

Did you test what would happen if you installed the package and wp-cli was already installed?

**Comment by ypid** [comment]
The package installs into a different path and `/usr/local/bin` is preferred so that the manual one is still being used. We can require `/usr/local/bin/wp` to be absent when going with the package.

**Comment by carlalexander** [comment]
Just wanted to drop a note here that new wp-cli was released today :)

**Comment by ypid** [comment]
Not sure yet when I will look into this again. I guess a few weeks :wink: If you want to give it a try, don’t hesitate.

**Comment by carlalexander** [comment]
I might soon. Been busy with Halloween as well :wink:

**Comment by carlalexander** [comment]
Created a commit under your name with the changes in the PR. Worked fine!

**Comment by ypid** [comment]
All right. Also an option :wink: Thanks.

**Pull request closed without merging**
